export enum Route {
  CompareTexts = "/compare-texts",
  JwtIO = "/jwt-io",
  Regex = "/regex",
  ReactPlayground = "/react-playground",
  WebViewPlayground = "/webview-playground",
  Markdown = "/markdown",
  GenerateAPIResponse = "/api-response",
  GenerateText = "/generate-text",
  NumberConverter = "/number-converter",
  RandomWheel = "/random-wheel",
  UIAccordion = "/accordion",
  UIAngleSlider = "/angle-slider",
  UIAutocomplete = "/autocomplete",
  UIAvatar = "/avatar",
  UIButton = "/button",
}
