export enum Route {
  CompareTexts = "/compare-texts",
  JwtIO = "/jwt-io",
  Regex = "/regex",
  ColorPicker = "/color-picker",
  ImageCrop = "/image-crop",
  ReactPlayground = "/react-playground",
  WebViewPlayground = "/webview-playground",
  Markdown = "/markdown",
  GenerateAPIResponse = "/api-response",
  GenerateQrCode = "/qr-code",
  GenerateText = "/generate-text",
  JsonFormatter = "/json-formatter",
  NumberConverter = "/number-converter",
  RandomWheel = "/random-wheel",
  UIAccordion = "/accordion",
  UIAngleSlider = "/angle-slider",
  UIAutocomplete = "/autocomplete",
  UIAvatar = "/avatar",
  UIBadge = "/badge",
  UIBreadcrumb = "/breadcrumb",
  UIButton = "/button",
  UIBrowserMockup = "/browser-mockup",
  UICarousel = "/carousel",
}
