export const JSON_SOURCE = `{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}`;

export const GRAPHQL_SOURCE = `type AutogeneratedMainType {
  userId: Int
  id: Int
  title: String
  completed: Boolean
}`;
