export enum VideoFormat {
  MP4 = "mp4",
  AVI = "avi",
  MKV = "mkv",
  MOV = "mov",
  FLV = "flv",
  WEBM = "webm",
  MPEG = "mpeg",
  TYPE_3GP = "3gp",
  OGV = "ogv",
  WMV = "wmv",
  ASF = "asf",
}

export const VIDEO_TYPES = {
  mp4: "video/mp4",
  avi: "video/x-msvideo",
  mkv: "video/x-matroska",
  mov: "video/quicktime",
  flv: "video/flv",
  webm: "video/webm",
  mpeg: "video/mpeg",
  ogv: "video/ogg",
  wmv: "video/x-ms-wmv",
  asf: "video/x-ms-asf",
  "3gp": "video/3gp",
} as const;

export const VIDEO_CONVERTERS: { [key: string]: VideoFormat[] } = {
  [VideoFormat.MP4]: [
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.AVI]: [
    VideoFormat.MP4,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.MKV]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.MOV]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.FLV]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.WEBM]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.MPEG]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.OGV]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.WMV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.WMV]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.ASF,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.ASF]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.TYPE_3GP,
  ],
  [VideoFormat.TYPE_3GP]: [
    VideoFormat.MP4,
    VideoFormat.AVI,
    VideoFormat.MKV,
    VideoFormat.MOV,
    VideoFormat.FLV,
    VideoFormat.WEBM,
    VideoFormat.MPEG,
    VideoFormat.OGV,
    VideoFormat.WMV,
    VideoFormat.ASF,
  ],
};

export const SUPPORTING_INPUT_FORMATS = Object.keys(
  VIDEO_CONVERTERS,
) as VideoFormat[];

export const EXTRA_SETTINGS: { [key: string]: string[] } = {
  [VideoFormat.WEBM]: ["-c:v", "libvpx", "-b:v", "1M", "-c:a", "libvorbis"],
};
