import { faker } from "@faker-js/faker/locale/en";

export const DEFAULT_API_FORMAT = `{
  "id": "string",
  "name": {
      "firstName": "string",
      "lastName": "string"
  },
  "age": "number",
  "phoneNumber": "string",
  "email": "string",
  "isMale": "boolean",
  "birthDate": "string",
  "companies": ["string"]
}`;

export const FAKER_KEYWORDS = [
  { keywords: ["aircraft", "aircrafts"], faker: faker.airline.aircraftType },
  {
    keywords: ["airline", "airlines", "airplane", "airplanes"],
    faker: faker.airline.airline,
  },
  { keywords: ["airport", "airports"], faker: faker.airline.airport },
  { keywords: ["bear", "bears"], faker: faker.animal.bear },
  { keywords: ["bird", "birds"], faker: faker.animal.bird },
  { keywords: ["cat", "cats"], faker: faker.animal.cat },
  { keywords: ["cetacean", "cetaceans"], faker: faker.animal.cetacean },
  { keywords: ["cow", "cows", "buffalo", "buffalos"], faker: faker.animal.cow },
  {
    keywords: [
      "crocodilia",
      "crocodiliaes",
      "crocodile",
      "crocodiles",
      "aligator",
      "aligators",
    ],
    faker: faker.animal.crocodilia,
  },
  { keywords: ["dog", "dogs", "puppy", "puppies"], faker: faker.animal.dog },
  { keywords: ["fish", "fishes"], faker: faker.animal.fish },
  { keywords: ["horse", "horses"], faker: faker.animal.horse },
  { keywords: ["insect", "insects"], faker: faker.animal.insect },
  { keywords: ["lion", "lions"], faker: faker.animal.lion },
  {
    keywords: ["rabbit", "rabbits", "bunny", "bunnies"],
    faker: faker.animal.rabbit,
  },
  { keywords: ["rodent", "rodents"], faker: faker.animal.rodent },
  {
    keywords: ["snake", "snakes", "python", "pythons"],
    faker: faker.animal.snake,
  },
  { keywords: ["animal", "animals"], faker: faker.animal.type },
  { keywords: ["cmyk"], faker: faker.color.cmyk },
  { keywords: ["hex", "hex_color", "hex_colors"], faker: faker.internet.color },
  { keywords: ["color", "colors"], faker: faker.color.human },
  { keywords: ["hsl", "hsl_color", "hsl_colors"], faker: faker.color.hsl },
  { keywords: ["hwb", "hwb_color", "hwb_colors"], faker: faker.color.hwb },
  { keywords: ["rgb", "rgb_color", "rgb_colors"], faker: faker.color.rgb },
  { keywords: ["department", "departments"], faker: faker.commerce.department },
  { keywords: ["isbn"], faker: faker.commerce.isbn },
  {
    keywords: ["price", "prices", "price_amount", "price_amounts"],
    faker: faker.commerce.price,
  },
  {
    keywords: ["product", "products", "product_name", "products_names"],
    faker: faker.commerce.productName,
  },
  {
    keywords: ["description", "descriptions"],
    faker: faker.commerce.productDescription,
  },
  {
    keywords: ["material", "materials"],
    faker: faker.commerce.productMaterial,
  },
  { keywords: ["company", "companies"], faker: faker.company.name },
  { keywords: ["collation", "collations"], faker: faker.database.collation },
  { keywords: ["column", "columns"], faker: faker.database.column },
  { keywords: ["date", "dates"], faker: faker.date.anytime },
  {
    keywords: ["month", "months"],
    faker: faker.date.month,
  },
  {
    keywords: ["timezone", "timezones"],
    faker: faker.location.timeZone,
  },
  {
    keywords: ["week", "weeks", "day", "days"],
    faker: faker.date.weekday,
  },
  {
    keywords: ["account", "accounts", "account_name", "account_names"],
    faker: faker.finance.accountName,
  },
  {
    keywords: ["amount", "amounts"],
    faker: faker.finance.amount,
  },
  {
    keywords: ["bitcoin", "bitcoins", "bitcoin_address", "bitcoin_addresses"],
    faker: faker.finance.bitcoinAddress,
  },
  {
    keywords: ["cvv"],
    faker: faker.finance.creditCardCVV,
  },
  {
    keywords: ["issuer", "issuers"],
    faker: faker.finance.creditCardIssuer,
  },
  {
    keywords: ["card", "cards", "card_number", "card_numbers"],
    faker: faker.finance.creditCardNumber,
  },
  {
    keywords: ["currency", "currencies"],
    faker: faker.finance.currencyName,
  },
  {
    keywords: [
      "ethereum",
      "ethereums",
      "ethereum_address",
      "ethereum_addresses",
    ],
    faker: faker.finance.ethereumAddress,
  },
  {
    keywords: ["iban"],
    faker: faker.finance.iban,
  },
  {
    keywords: [
      "litecoin",
      "litecoins",
      "litecoin_address",
      "litecoin_addresses",
    ],
    faker: faker.finance.litecoinAddress,
  },
  {
    keywords: ["mask", "masks", "mask_number", "mask_numbers"],
    faker: faker.finance.maskedNumber,
  },
  {
    keywords: ["pin", "pins"],
    faker: faker.finance.pin,
  },
  {
    keywords: [
      "transaction",
      "transactions",
      "transaction_type",
      "transaction_types",
    ],
    faker: faker.finance.transactionType,
  },
  {
    keywords: ["branch", "branches", "branch_name", "branch_names"],
    faker: faker.git.branch,
  },
  {
    keywords: ["commit", "commits", "commit_message", "commit_messages"],
    faker: faker.git.commitMessage,
  },
  {
    keywords: ["sha"],
    faker: faker.git.commitSha,
  },
  {
    keywords: ["hack"],
    faker: faker.hacker.phrase,
  },
  {
    keywords: [
      "avatar",
      "avatars",
      "avatar_image",
      "avatar_images",
      "avatar_link",
      "avatar_links",
      "avatar_url",
      "avatar_urls",
      "avatar_path",
      "avatar_paths",
      "img",
      "img_link",
      "img_links",
      "img_url",
      "img_urls",
      "img_path",
      "img_paths",
      "image",
      "images",
      "image_link",
      "image_links",
      "image_url",
      "image_urls",
      "image_path",
      "image_paths",
      "photo",
      "photos",
      "photo_link",
      "photo_links",
      "photo_url",
      "photo_urls",
      "photo_path",
      "photo_paths",
    ],
    faker: faker.image.avatar,
  },
  {
    keywords: ["uri", "uris"],
    faker: faker.image.dataUri,
  },
  {
    keywords: ["url", "urls"],
    faker: faker.image.url,
  },
  {
    keywords: ["domain", "domains", "domain_name", "domain_names"],
    faker: faker.internet.domainName,
  },
  {
    keywords: [
      "mail",
      "mails",
      "mail_address",
      "mails",
      "mail_addresses",
      "email",
      "emails",
      "email_address",
      "emails",
      "email_addresses",
      "hotmail",
      "hotmails",
      "hotmail_address",
      "hotmails",
      "hotmail_addresses",
      "outlook",
      "outlooks",
      "outlook_address",
      "outlooks",
      "outlook_addresses",
    ],
    faker: faker.internet.email,
  },
  {
    keywords: ["emoji", "emojies"],
    faker: faker.internet.emoji,
  },
  {
    keywords: [
      "method",
      "methods",
      "method_name",
      "method_names",
      "method_type",
      "method_types",
    ],
    faker: faker.internet.httpMethod,
  },
  {
    keywords: ["status_code", "status_codes"],
    faker: faker.internet.httpStatusCode,
  },
  {
    keywords: ["ip", "ip_address", "ip_addresses"],
    faker: faker.internet.ip,
  },
  {
    keywords: [
      "ipv4",
      "ip_v4",
      "ipv4_address",
      "ip_v4_address",
      "ipv4_addresses",
      "ip_v4_addresses",
    ],
    faker: faker.internet.ipv4,
  },
  {
    keywords: [
      "ipv6",
      "ip_v6",
      "ipv6_address",
      "ip_v6_address",
      "ipv6_addresses",
      "ip_v6_addresses",
    ],
    faker: faker.internet.ipv6,
  },
  {
    keywords: ["pass", "password", "passwords"],
    faker: faker.internet.password,
  },
  {
    keywords: ["port", "ports"],
    faker: faker.internet.port,
  },
  {
    keywords: ["protocol", "protocols", "protocol_name", "protocol_names"],
    faker: faker.internet.protocol,
  },
  {
    keywords: ["agent", "agents", "agent_name", "agent_names"],
    faker: faker.internet.userAgent,
  },
  {
    keywords: ["username", "usernames", "user_name", "user_names"],
    faker: faker.internet.userName,
  },
  {
    keywords: ["direction", "directions"],
    faker: faker.location.direction,
  },
  {
    keywords: ["city", "cities"],
    faker: faker.location.city,
  },
  {
    keywords: [
      "country",
      "countries",
      "region",
      "regions",
      "nation",
      "nations",
      "nationality",
      "nationalities",
    ],
    faker: faker.location.country,
  },
  {
    keywords: ["county", "counties"],
    faker: faker.location.county,
  },
  {
    keywords: [
      "lat",
      "lat_position",
      "lat_positions",
      "lat_location",
      "lat_locations",
      "lat_number",
      "lat_numbers",
      "lat_value",
      "lat_values",
      "latitude",
      "latitude_position",
      "latitude_positions",
      "latitude_location",
      "latitude_locations",
      "latitude_number",
      "latitude_numbers",
      "latitude_value",
      "latitude_values",
    ],
    faker: faker.location.latitude,
  },
  {
    keywords: [
      "lng",
      "lng_position",
      "lng_positions",
      "lng_location",
      "lng_locations",
      "lng_number",
      "lng_numbers",
      "lng_value",
      "lng_values",
      "long",
      "long_position",
      "long_positions",
      "long_location",
      "long_locations",
      "long_number",
      "long_numbers",
      "long_value",
      "long_values",
      "longitude",
      "longitude_position",
      "longitude_positions",
      "longitude_location",
      "longitude_locations",
      "longitude_number",
      "longitude_numbers",
      "longitude_value",
      "longitude_values",
    ],
    faker: faker.location.longitude,
  },
  {
    keywords: ["street", "streets", "street_name", "street_names"],
    faker: faker.location.street,
  },
  {
    keywords: ["address", "addresses"],
    faker: faker.location.streetAddress,
  },
  {
    keywords: ["zip", "zipcode", "zipcodes", "zip_code", "zip_codes"],
    faker: faker.location.zipCode,
  },
  {
    keywords: [
      "genre",
      "genres",
      "genre_type",
      "genre_types",
      "genre_name",
      "genre_names",
    ],
    faker: faker.music.genre,
  },
  {
    keywords: ["song", "songs", "song_name", "song_names"],
    faker: faker.music.songName,
  },
  {
    keywords: ["bio", "bios", "biography", "biographies"],
    faker: faker.person.bio,
  },
  {
    keywords: ["middlename", "firstnames", "first_name", "first_names"],
    faker: faker.person.firstName,
  },
  {
    keywords: ["middlename", "middlenames", "middle_name", "middle_names"],
    faker: faker.person.middleName,
  },
  {
    keywords: ["lastname", "lastnames", "last_name", "last_names"],
    faker: faker.person.lastName,
  },
  {
    keywords: ["gender", "genders", "gender_type", "gender_types"],
    faker: faker.person.gender,
  },
  {
    keywords: ["sex"],
    faker: faker.person.sex,
  },
  {
    keywords: [
      "job",
      "jobs",
      "job_title",
      "job_titles",
      "job_name",
      "job_names",
    ],
    faker: faker.person.jobTitle,
  },
  {
    keywords: ["zodiac", "zodiac_sign"],
    faker: faker.person.zodiacSign,
  },
  {
    keywords: [
      "imei",
      "imei_number",
      "imei_numbers",
      "imei_value",
      "imei_values",
    ],
    faker: faker.phone.imei,
  },
  {
    keywords: [
      "phone",
      "phones",
      "phone_number",
      "phone_numbers",
      "fax",
      "faxes",
      "fax_number",
      "fax_numbers",
      "dial",
      "dials",
      "dial_number",
      "dial_numbers",
    ],
    faker: faker.phone.number,
  },
  {
    keywords: ["binary", "binaries", "binary_number", "binary_numbers"],
    faker: faker.string.binary,
  },
  {
    keywords: ["bit", "bit_number", "bit_value", "bit_numbers", "bit_values"],
    faker: faker.string.binary,
  },
  {
    keywords: [
      "hexa",
      "hexa_number",
      "hexa_value",
      "hexa_numbers",
      "hexa_values",
      "hexadecimal",
      "hexadecimal_number",
      "hexadecimal_value",
      "hexadecimal_numbers",
      "hexadecimal_values",
      "hexa_decimal",
      "hexa_decimal_number",
      "hexa_decimal_value",
      "hexa_decimal_numbers",
      "hexa_decimal_values",
    ],
    faker: faker.string.hexadecimal,
  },
  {
    keywords: [
      "octal",
      "octal_number",
      "octal_value",
      "octal_numbers",
      "octal_values",
    ],
    faker: faker.string.octal,
  },
  {
    keywords: ["symbol", "symbols"],
    faker: faker.string.symbol,
  },
  {
    keywords: [
      "id",
      "uuid",
      "uuid_value",
      "uuid_values",
      "uuid_string",
      "uuid_strings",
    ],
    faker: faker.string.uuid,
  },
  {
    keywords: [
      "ext",
      "extension",
      "extensions",
      "extension_type",
      "extension_types",
    ],
    faker: faker.system.fileExt,
  },
  {
    keywords: ["file_type", "file_types"],
    faker: faker.system.commonFileType,
  },
  {
    keywords: ["file", "files", "file_name", "file_names"],
    faker: faker.system.commonFileName,
  },
  {
    keywords: ["cron", "crons"],
    faker: faker.system.cron,
  },
  {
    keywords: [
      "dir",
      "directory",
      "directories",
      "directory_path",
      "directory_paths",
      "folder",
      "folders",
      "folder_path",
      "folder_paths",
    ],
    faker: faker.system.directoryPath,
  },
  {
    keywords: ["mime"],
    faker: faker.system.mimeType,
  },
  {
    keywords: ["semver", "semvers", "semantic_version", "semantic_versions"],
    faker: faker.system.semver,
  },
  {
    keywords: ["bicycle", "bicycles"],
    faker: faker.vehicle.bicycle,
  },
  {
    keywords: ["fuel"],
    faker: faker.vehicle.fuel,
  },
  {
    keywords: [
      "manufacturer",
      "manufacturers",
      "manufacturer_name",
      "manufacturer_names",
    ],
    faker: faker.vehicle.manufacturer,
  },
  {
    keywords: ["model", "models"],
    faker: faker.vehicle.model,
  },
  {
    keywords: ["vehicle", "vehicles"],
    faker: faker.vehicle.vehicle,
  },
  {
    keywords: [
      "name",
      "names",
      "fullname",
      "fullnames",
      "full_name",
      "full_names",
      "person_name",
      "person_name",
    ],
    faker: faker.person.fullName,
  },
];
