import type { UIField } from "@/app/(ui-libs)/_components/ui-docs";

export const tableProperties: UIField[] = [
  {
    name: "stickyHeader",
    description: "Whether header is sticky to top",
    default: "false",
    required: false,
    type: "boolean",
  },
  {
    name: "variant",
    description: "Theme variant of Table",
    default: '"outline"',
    required: false,
    type: "radio",
    radioList: ["outline", "underline", "bordered"],
  },
  {
    name: "selectionMode",
    description: "Select row mode of Table",
    default: '"none"',
    required: false,
    type: "radio",
    radioList: ["none", "single", "multiple"],
  },
  {
    name: "color",
    description: "Color of Table",
    default: '"primary"',
    required: false,
    type: "radio",
    radioList: [
      "primary",
      "secondary",
      "success",
      "danger",
      "warning",
      "info",
      "light",
      "dark",
    ],
  },
  {
    name: "className",
    description: "Wrapper class",
    default: null,
    required: false,
    type: "none",
  },
  {
    name: "keyField",
    description: "Key field of Table data",
    default: null,
    required: true,
    type: "none",
  },
  {
    name: "header",
    description: "List of Table header",
    default: null,
    required: true,
    type: "none",
    typeLabel: "TableColumn[]",
  },
  {
    name: "data",
    description: "List of Table data",
    default: null,
    required: true,
    type: "none",
  },
  {
    name: "selections",
    description: "List of selected ids",
    default: null,
    required: false,
    type: "none",
    typeLabel: "string[]",
  },
  {
    name: "onChangeSelections",
    description: "Change select row event",
    default: null,
    required: false,
    type: "none",
    typeLabel: "(ids: string[]) => void",
  },
];
